name: API and WEB UI tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  api-web-ui-tests:

    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1.6.2

    - name: Setup gradlew
      run: chmod +x gradlew
      
    - name: Execute Test
      run: ./gradlew cucumber
